### ISSUE TITLE
TypeError: Cannot set property 'name' of undefined

### ISSUE THREAD

**Issue by kajackdfw** [noprotocol/generator-np-laravel#3]
yo np-laravel
   NOPROTOCOL://                                   

? The current directory /var/www/html/Estimutt_v2 is not empty. Continue? Yes
     info App configuration
? Project name Estimutt_v2
? Project version 2.0.1
? Which version of Laravel would you like to install? 
 (v5.1.1 is the last one tested/considered stable for this generator). v5.1.1
? Would you like to setup a database? No
? Would you like to setup a git repository? No
✔ Downloading Laravel v5.1.1
     info ... Fetching https://github.com/laravel/laravel/archive/v5.1.1.tar.gz ...
     info This might take a few moments
.✔ Done in .
✔ Removing default Laravel files
✔ Setting up frontend build config
✔ Setting up frontend files and directories
✔ Setting up assets files and directories
✔ Setting up views and layout resources
✔ Setting up backend (routes, controllers, NoProtocol splash page, etc)
✔ Setting up documentation
✔ Changing file rights
✔ Patching bower.json

/var/www/html/Estimutt_v2/node_modules/generator-np-laravel/app/index.js:425
    data.name = 'noprotocol/'+settings.appName;
              ^
TypeError: Cannot set property 'name' of undefined
    at /var/www/html/Estimutt_v2/node_modules/generator-np-laravel/app/index.js:425:15
    at /var/www/html/Estimutt_v2/node_modules/generator-np-laravel/node_modules/fs-extra/node_modules/jsonfile/index.js:10:21
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)

**Comment by bjrnblm** [comment]
Cannot reproduce this:

```
? The current directory /Users/bjorn/Estimutt_v2 is not empty. Continue? Yes
     info App configuration
? Project name Estimutt_v2
? Project version 2.0.1
? Which version of Laravel would you like to install? 
 (v5.1.1 is the last one tested/considered stable for this generator). v5.1.1
? Would you like to setup a database? No
? Would you like to setup a git repository? No
✔ Downloading Laravel v5.1.1
     info ... Fetching https://github.com/laravel/laravel/archive/v5.1.1.tar.gz ...
     info This might take a few moments
.✔ Done in .
✔ Removing default Laravel files
✔ Setting up frontend build config
✔ Setting up frontend files and directories
✔ Setting up assets files and directories
✔ Setting up views and layout resources
✔ Setting up backend (routes, controllers, NoProtocol splash page, etc)
✔ Setting up documentation
✔ Changing file rights
✔ Patching bower.json
✔ Patching package.json
✔ Patching composer.json
✔ Skipping database setup
✔ Installing PHP/Composer dependancies
✔ Installing NPM dependencies
✔ Installing Bower dependencies
✔ Setting up Laravel config
✔ Installion completed with 0 errors.
➜  Estimutt_v2
```

What versions are you running for these packages?

```
node -v
npm -v
yo --version
bower -v
composer --version
```

**Comment by kajackdfw** [comment]
kajack> node -vv0.10.32kajack> npm -v2.1.2kajack> yo --version1.4.8kajack> bower -v1.5.2kajack> composer --versionComposer version 1.0-dev (c557715669ba8dd2dc6c63859f919351a4aa5e2f) 2015-10-28 14:13:03

```
  From: Björn Blom <notifications@github.com>
```

 To: noprotocol/generator-np-laravel generator-np-laravel@noreply.github.com 
Cc: Kelly Taylor kajackdfw@yahoo.com 
 Sent: Thursday, November 5, 2015 4:08 PM
 Subject: Re: [generator-np-laravel] TypeError: Cannot set property 'name' of undefined (#3)

Cannot reproduce this:? The current directory /Users/bjorn/Estimutt_v2 is not empty. Continue? Yes
     info App configuration
? Project name Estimutt_v2
? Project version 2.0.1
? Which version of Laravel would you like to install? 
 (v5.1.1 is the last one tested/considered stable for this generator). v5.1.1
? Would you like to setup a database? No
? Would you like to setup a git repository? No
✔ Downloading Laravel v5.1.1
     info ... Fetching https://github.com/laravel/laravel/archive/v5.1.1.tar.gz ...
     info This might take a few moments
.✔ Done in .
✔ Removing default Laravel files
✔ Setting up frontend build config
✔ Setting up frontend files and directories
✔ Setting up assets files and directories
✔ Setting up views and layout resources
✔ Setting up backend (routes, controllers, NoProtocol splash page, etc)
✔ Setting up documentation
✔ Changing file rights
✔ Patching bower.json
✔ Patching package.json
✔ Patching composer.json
✔ Skipping database setup
✔ Installing PHP/Composer dependancies
✔ Installing NPM dependencies
✔ Installing Bower dependencies
✔ Setting up Laravel config
✔ Installion completed with 0 errors.
➜  Estimutt_v2
What versions are you running for these packages?node -v
npm -v
yo --version
bower -v
composer --version
